export const ACHIEVEMENTS = [
  {
    completed: false,
    id: 1,
    name: "First win",
    description: "Win a game",
    text: "You won your first game",
    imageUrl: "/achievements/first-win.svg",
    disabled: false,
  },
  {
    completed: false,
    id: 2,
    name: "First lose",
    description: "Lose a game",
    text: "You lost your first game",
    imageUrl: "/achievements/first-lose.svg",
    disabled: false,
  },
  {
    completed: false,
    id: 3,
    name: "3 wins in a row",
    description: "Win 3 games in a row",
    text: "You won 3 games in a row",
    imageUrl: "/achievements/3-wins-in-a-row.svg",
    disabled: false,
  },
  {
    completed: false,
    id: 4,
    name: "3 loses in a row",
    description: "Lose 3 games in a row",
    text: "You lost 3 games in a row",
    imageUrl: "/achievements/3-loses-in-a-row.svg",
    disabled: false,
  },
  {
    completed: false,
    id: 5,
    name: "Road to hero",
    description: "lose a game and then win one",
    text: "You lost a game and then won one",
    imageUrl: "/achievements/road-to-hero.svg",
    disabled: false,
  },
  {
    completed: false,
    id: 6,
    name: "404 ice cream",
    description: "Secret achievement",
    text: "You found a secret achievement",
    imageUrl: "/achievements/404-achievement.svg",
    disabled: false,
  },
];
